wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1661490134
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 13
      4: 3.10.4
      5: 0.12.14
      8:
      - 5
batch_size:
  desc: null
  value: 2
data_city_list:
  desc: null
  value: ./dataset/cityscapes_list/clear_lindau.txt
data_dir:
  desc: null
  value: /root/data1
data_dir_cwsf:
  desc: null
  value: /root/data1/Cityscapes
data_dir_rf:
  desc: null
  value: /root/data1
data_list:
  desc: null
  value: ./dataset/cityscapes_list/train_foggy_0.005.txt
data_list_cwsf:
  desc: null
  value: ./dataset/cityscapes_list/train_origin.txt
data_list_rf:
  desc: null
  value: /root/data1/Foggy_Zurich/lists_file_names/RGB_sum_filenames.txt
file_name:
  desc: null
  value: xyz
gpu:
  desc: null
  value: 0
input_size:
  desc: null
  value: 2048,1024
input_size_rf:
  desc: null
  value: 1920,1080
iter_size:
  desc: null
  value: 1
lambda_con:
  desc: null
  value: 0.0001
lambda_fsm:
  desc: null
  value: 1.0e-07
modeltrain:
  desc: null
  value: train
num_classes:
  desc: null
  value: 19
num_steps:
  desc: null
  value: 100000
num_steps_stop:
  desc: null
  value: 60000
num_workers:
  desc: null
  value: 4
random_seed:
  desc: null
  value: 1234
restore_from:
  desc: null
  value: no_model
restore_from_fogpass:
  desc: null
  value: no_model
save_pred_every:
  desc: null
  value: 100
set:
  desc: null
  value: train
snapshot_dir:
  desc: null
  value: /home/river/nishka/fifo/snapshots
